rpms:
  - zenity
  - alacritty
  - python3-psutil
  - bridge-utils
  - vagrant-libvirt
  - virt-install
  - virt-manager
  - edk2-ovmf
  - swtpm
flatpaks:
  - org.mozilla.firefox
  - com.mattjakeman.ExtensionManager
  - org.libreoffice.LibreOffice
  - org.gustavoperedo.FontDownloader
  - com.github.tchx84.Flatseal
